# Generated by Django 6.0 on 2025-12-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HolaMundo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='mail',
            field=models.EmailField(default='', max_length=254, verbose_name='Correo electromagnetico'),
        ),
    ]
