# Generated by Django 6.0.1 on 2026-02-02 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rango', models.CharField(choices=[('Bronce', 'Bronce'), ('Plata', 'Plata'), ('Oro', 'Oro'), ('Platino', 'Platino'), ('Diamante', 'Diamante'), ('Campeon', 'Campeon'), ('Gran Campeon', 'Gran Campeon'), ('Supersonico', 'Supersonico')], default='Bronce', max_length=20)),
                ('plataforma', models.CharField(choices=[('PC', 'PC'), ('PS4', 'PS4'), ('PS5', 'PS5'), ('Xbox One', 'Xbox One'), ('Xbox Series X', 'Xbox Series X'), ('Nintendo Switch', 'Nintendo Switch')], default='PC', max_length=20)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='torneos.equipo')),
            ],
        ),
    ]
