# Generated by Django 6.0 on 2026-02-06 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0002_alter_jugador_equipo_torneo_partido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='creado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='torneos_creados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
